### 2-2-1 Numpy的匯入

In [3]:
import numpy as np

# 意指顯示到小數點後第3位
%precision 3

'%.3f'

### 2-2-2 陣列的操作

In [29]:
data = np.array([9,2,3,4,10,6,7,8,1,5])
print(data)

[ 9  2  3  4 10  6  7  8  1  5]


In [18]:
# 查看資料型別(type)
data.dtype

dtype('int64')

In [19]:
# 維度與元素數量
print('維度：',data.ndim)
print('元素數量：',data.size)

維度： 1
元素數量： 10


In [21]:
# 對所有的元素進行運算
print(data * 2)

[18  4  6  8 20 12 14 16  2 10]


In [22]:
print('乘法運算：', np.array([1,2,3,4,5,6,7,8,9,10]) * np.array([10,9,8,7,6,5,4,3,2,1]))
print('連乘：',np.array([1,2,3,4,5,6,7,8,9,10]) ** 2)
print('除法運算：',np.array([1,2,3,4,5,6,7,8,9,10]) / np.array([10,9,8,7,6,5,4,3,2,1]))

乘法運算： [10 18 24 28 30 30 28 24 18 10]
連乘： [  1   4   9  16  25  36  49  64  81 100]
除法運算： [ 0.1    0.222  0.375  0.571  0.833  1.2    1.75   2.667  4.5   10.   ]


In [31]:
# 排序
print('原本的值：',data)

print('排序之後：',np.sort(data))

# 使用sort後會取代原本的資料(data)。再次顯示data會是排序後的資料

原本的值： [ 9  2  3  4 10  6  7  8  1  5]
排序之後： [ 1  2  3  4  5  6  7  8  9 10]


In [32]:
data[::-1].sort()
print('排序之後：',data)

排序之後： [10  9  8  7  6  5  4  3  2  1]


In [36]:
# 最小值
print('Min:',data.min())
# 最大值
print('Max:',data.max())
# 總和
print('Sum:',data.sum())
# 累積和
print('Cum:',data.cumsum())
# 累積比例
print('Ratio:',data.cumsum() / data.sum())

Min: 1
Max: 10
Sum: 55
Cum: [10 19 27 34 40 45 49 52 54 55]
Ratio: [0.182 0.345 0.491 0.618 0.727 0.818 0.891 0.945 0.982 1.   ]


### 2-2-3 亂數

In [12]:
import numpy.random as random

In [73]:
# 設一個固定值可確保每次執行的隨機數相同
random.seed(0)

# 產生常態分佈（平均為０、標準差為１）的10個亂數
rnd_data = random.randn(10)

print('含有10個亂數的陣列：',rnd_data)

含有10個亂數的陣列： [ 1.764  0.4    0.979  2.241  1.868 -0.977  0.95  -0.151 -0.103  0.411]


In [69]:
# 要取出的對象資料
data = np.array([9,2,3,4,10,6,7,8,1,5])

# 隨機取出
# 取出10個（允許重複，放回抽樣）
print(random.choice(data,20))
# 取出10個（不允許重複，不放回抽樣）
print(random.choice(data,10,replace = False))

[5 8 4 4 1 4 1 3 7 6 7 8 5 7 7 5 4 1 2 3]
[ 6  1  7  4 10  9  2  5  8  3]


##### 證明Numpy比較快

In [76]:
# N是亂數的生成數量，10的6次方
N = 10 ** 6

# Python版本
# 「_」是慣例上表示不參照代入值的變數名稱
# 比如說，雖然相同於寫成for a in range(N)，但寫成a則該值可在之後使用
# 如果不打算參照該值，慣例上會寫成for _ in range(N)
normal_data = [random.random() for _ in range(N)]

# Numpy版
numpy_random_data = np.array(normal_data)

# calc time:總和
# 一般的處理
%timeit sum(normal_data)

# 使用Numpy的處理
%timeit np.sum(numpy_random_data)


4.82 ms ± 26.8 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
203 µs ± 6.39 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


### 2-2-4 矩陣

In [78]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
array1 = np.arange(9).reshape(3,3)
print(array1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [5]:
# 索引值擺前面表示顯示row
print(array1[0,:])
print(array1[2,:])
print(array1[1,:])

[0 1 2]
[6 7 8]
[3 4 5]


In [6]:
# 索引值擺前面表示顯示column
print(array1[:,0])
print(array1[:,1])
print(array1[:,2])

[0 3 6]
[1 4 7]
[2 5 8]


In [8]:
array2 = np.arange(9,18).reshape(3,3)
print(array2)

[[ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [9]:
# 矩陣之積
np.dot(array1,array2)

array([[ 42,  45,  48],
       [150, 162, 174],
       [258, 279, 300]])

In [10]:
# 元素各自之積
array1 * array2

array([[  0,  10,  22],
       [ 36,  52,  70],
       [ 90, 112, 136]])

In [93]:
((row,column),dtype)
print(np.zeros((2,3),dtype = np.int64))
print(np.ones((2,3),dtype = np.float64))

[[0 0 0]
 [0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]]


##### 練習2-1

In [95]:
a = np.arange(51)
print(np.sum(a))

1275


##### 練習2-2

In [13]:
random.seed(0)
array_random = np.array(random.randn(10))
print(array_random)
print('最小值：',array_random.min())
print('最大值：',array_random.max())
print('總和：',array_random.sum())

[ 1.764  0.4    0.979  2.241  1.868 -0.977  0.95  -0.151 -0.103  0.411]
最小值： -0.977277879876411
最大值： 2.240893199201458
總和： 7.380231707288347


In [145]:
array_3 = np.ones((5,5),dtype = 'i') * 3
print(array_3.dot(array_3))

[[45 45 45 45 45]
 [45 45 45 45 45]
 [45 45 45 45 45]
 [45 45 45 45 45]
 [45 45 45 45 45]]
