####  2-3-1 Scipy的函式庫匯入

In [6]:
# 用於線性代數的函式庫
import scipy.linalg as linalg

# 用於最佳化計算（最小值）的函式
from scipy.optimize import minimize_scalar

#### 2-3-2 矩陣運算

In [13]:
import numpy as np
matrix = np.array([[1,-1,-1],[-1,1,-1],[-1,-1,1]])

print('matrix')
print(matrix)
print('行列式')
print(linalg.det(matrix))

matrix
[[ 1 -1 -1]
 [-1  1 -1]
 [-1 -1  1]]
行列式
-4.0


In [14]:
# 反矩陣
print('反矩陣')
print(linalg.inv())

反矩陣
[[ 0.  -0.5 -0.5]
 [-0.5 -0.  -0.5]
 [-0.5 -0.5  0. ]]


In [15]:
# 確認原始矩陣與反矩陣相乘為零矩陣
print(matrix.dot(linalg.inv(matrix)))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
# 特徵值與特徵向量
eig_value, eig_vector = linalg.eig(matrix)


print('特徵值')
print(eig_value)
print('特徵向量')
print(eig_vector

特徵值
[-1.+0.j  2.+0.j  2.+0.j]
特徵向量
[[ 0.57735027  0.81649658  0.40824829]
 [ 0.57735027 -0.40824829 -0.81649658]
 [ 0.57735027 -0.40824829  0.40824829]]


#### 2-3-3 牛頓法

In [18]:
def my_function(x):
    return (x**2 + 2*x + 1)

from scipy.optimize import newton

print(newton(my_function,0))

-0.999999985174924


In [19]:
print(minimize_scalar(my_function, method = 'Brent'))

     fun: 0.0
    nfev: 9
     nit: 4
 success: True
       x: -1.0000000000000002


##### 練習問題2-4

In [21]:
Matrix_a = np.array([[1,2,3],[1,3,2],[3,1,2]])
print(linalg.det(Matrix_a))

-12.0


In [28]:
print('反矩陣\n',linalg.inv(Matrix_a))
Matrix_a_value ,Matrix_a_vector =  linalg.eig(Matrix_a)
print('特徵值\n', Matrix_a_value)
print('特徵向量\n',Matrix_a_vector)

反矩陣
 [[-0.33333333  0.08333333  0.41666667]
 [-0.33333333  0.58333333 -0.08333333]
 [ 0.66666667 -0.41666667 -0.08333333]]
特徵值
 [ 6.        +0.j -1.41421356+0.j  1.41421356+0.j]
特徵向量
 [[-0.57735027 -0.72236645  0.16041816]
 [-0.57735027 -0.14290228 -0.81090869]
 [-0.57735027  0.67658381  0.56275492]]


In [29]:
def function(x):
    return (x**3 + 2*x + 1)

print(newton(function,0))

-0.45339765151640365
